"""Man-page (roff) reader/writer — constrained slice."""
from __future__ import annotations

import re
from pandoc_py.ast import (
    BulletList, CodeBlock, Document, Heading, OrderedList, Paragraph,
)
from pandoc_py.io import Reader, Writer, register_reader, register_writer
from ._common import block_text_paragraphs, inlines_to_plain, text_to_inlines


def _read_man(source: str) -> Document:
    text = source.replace('\r\n', '\n').replace('\r', '\n')
    lines = text.split('\n')
    blocks = []
    i = 0
    para_buf: list[str] = []

    def flush_para():
        nonlocal para_buf
        if para_buf:
            blocks.append(Paragraph(inlines=text_to_inlines(' '.join(para_buf))))
            para_buf = []

    while i < len(lines):
        line = lines[i]
        m = re.match(r'^\.SH\s+(.*)$', line)
        if m:
            flush_para()
            blocks.append(Heading(level=1, inlines=text_to_inlines(m.group(1).strip().strip('"'))))
            i += 1; continue
        m = re.match(r'^\.SS\s+(.*)$', line)
        if m:
            flush_para()
            blocks.append(Heading(level=2, inlines=text_to_inlines(m.group(1).strip().strip('"'))))
            i += 1; continue
        if line.startswith('.PP') or line.startswith('.LP') or line.startswith('.P '):
            flush_para()
            i += 1; continue
        if line.startswith('.\\"'):  # comment
            i += 1; continue
        if not line.strip():
            flush_para(); i += 1; continue
        para_buf.append(line)
        i += 1
    flush_para()
    return Document(blocks=blocks, source_format='man')


def _write_man(document: Document) -> str:
    out: list[str] = ['.\\" Generated by pandoc_py']
    for block in document.blocks:
        if isinstance(block, Heading):
            tag = '.SH' if block.level <= 1 else '.SS'
            out.append(f'{tag} "{inlines_to_plain(block.inlines)}"')
        elif isinstance(block, Paragraph):
            out.append('.PP')
            out.append(inlines_to_plain(block.inlines))
        elif isinstance(block, (BulletList, OrderedList)):
            for item in block.items:
                for sub in block_text_paragraphs(item):
                    out.append('.IP \\(bu')
                    out.append(sub)
        elif isinstance(block, CodeBlock):
            out.append('.nf')
            for ln in block.text.split('\n'): out.append(ln)
            out.append('.fi')
    return '\n'.join(out) + '\n'


class ManReader(Reader):
    format_name = 'man'
    aliases = ('roff',)
    def read(self, source, options=None):
        if isinstance(source, bytes): source = source.decode('utf-8')
        return _read_man(source)


class ManWriter(Writer):
    format_name = 'man'
    aliases = ('roff',)
    def write(self, document, options=None):
        return _write_man(document)


register_reader(ManReader())
register_writer(ManWriter())
