"""mdoc (BSD man-page) reader/writer — constrained slice."""
from __future__ import annotations

import re

from pandoc_py.ast import (
    BulletList, CodeBlock, Document, Heading, OrderedList, Paragraph,
)
from pandoc_py.io import Reader, Writer, register_reader, register_writer
from ._common import block_text_paragraphs, inlines_to_plain, text_to_inlines


def _read_mdoc(source: str) -> Document:
    """mdoc reader.

    mdoc uses different macros than `man(7)`:
      ``.Sh`` for section headings, ``.Pp`` for paragraph break,
      ``.Bl -bullet`` / ``.It`` / ``.El`` for bullet lists,
      ``.Bd -literal`` / ``.Ed`` for code blocks.
    """
    text = source.replace('\r\n', '\n').replace('\r', '\n')
    lines = text.split('\n')
    blocks: list = []
    para_buf: list[str] = []

    def flush():
        nonlocal para_buf
        if para_buf:
            blocks.append(Paragraph(inlines=text_to_inlines(' '.join(para_buf))))
            para_buf = []

    i = 0
    while i < len(lines):
        line = lines[i]
        m = re.match(r'^\.Sh\s+(.*)$', line)
        if m:
            flush()
            blocks.append(Heading(level=1, inlines=text_to_inlines(m.group(1).strip().strip('"'))))
            i += 1; continue
        m = re.match(r'^\.Ss\s+(.*)$', line)
        if m:
            flush()
            blocks.append(Heading(level=2, inlines=text_to_inlines(m.group(1).strip().strip('"'))))
            i += 1; continue
        if line.startswith('.Pp') or line.startswith('.Lp'):
            flush(); i += 1; continue
        if line.startswith(r'.\"'):
            i += 1; continue
        if line.startswith('.Bl'):
            flush()
            items: list = []
            j = i + 1
            current_item: list[str] = []
            while j < len(lines) and not lines[j].startswith('.El'):
                if lines[j].startswith('.It'):
                    if current_item:
                        items.append([Paragraph(inlines=text_to_inlines(' '.join(current_item)), is_plain=True)])
                    current_item = []
                    rest = lines[j][3:].strip()
                    if rest:
                        current_item.append(rest)
                elif lines[j].strip() and not lines[j].startswith('.'):
                    current_item.append(lines[j].strip())
                j += 1
            if current_item:
                items.append([Paragraph(inlines=text_to_inlines(' '.join(current_item)), is_plain=True)])
            if items:
                blocks.append(BulletList(items=items))
            i = j + 1; continue
        if line.startswith('.Bd'):
            flush()
            buf, j = [], i + 1
            while j < len(lines) and not lines[j].startswith('.Ed'):
                buf.append(lines[j]); j += 1
            blocks.append(CodeBlock(text='\n'.join(buf)))
            i = j + 1; continue
        if not line.strip():
            flush(); i += 1; continue
        para_buf.append(line)
        i += 1
    flush()
    return Document(blocks=blocks, source_format='mdoc')


def _write_mdoc(document: Document) -> str:
    out: list[str] = ['.\\" Generated by pandoc_py']
    for block in document.blocks:
        if isinstance(block, Heading):
            tag = '.Sh' if block.level <= 1 else '.Ss'
            out.append(f'{tag} {inlines_to_plain(block.inlines)}')
        elif isinstance(block, Paragraph):
            out.append('.Pp')
            out.append(inlines_to_plain(block.inlines))
        elif isinstance(block, (BulletList, OrderedList)):
            out.append('.Bl -bullet' if isinstance(block, BulletList) else '.Bl -enum')
            for item in block.items:
                for sub in block_text_paragraphs(item):
                    out.append(f'.It {sub}')
            out.append('.El')
        elif isinstance(block, CodeBlock):
            out.append('.Bd -literal')
            for ln in block.text.split('\n'): out.append(ln)
            out.append('.Ed')
    return '\n'.join(out) + '\n'


class MdocReader(Reader):
    format_name = 'mdoc'
    def read(self, source, options=None):
        if isinstance(source, bytes): source = source.decode('utf-8')
        return _read_mdoc(source)


class MdocWriter(Writer):
    format_name = 'mdoc'
    def write(self, document, options=None):
        return _write_mdoc(document)


register_reader(MdocReader())
register_writer(MdocWriter())
